In [1]:
print(4*(5+6))

44


In [2]:
type

type

In [3]:
type(3+1.4+5)

float

In [4]:
list = [1,2,[3,4,'Chaitanya']]

In [5]:
list

[1, 2, [3, 4, 'Chaitanya']]

In [6]:
list[1:]

[2, [3, 4, 'Chaitanya']]

In [7]:
list[4]

IndexError: list index out of range

In [8]:
list[3:]

[]

In [9]:
list[2:]

[[3, 4, 'Chaitanya']]

In [10]:
list[2][2]

'Chaitanya'

In [11]:
2**2

4

In [12]:
3**3

27

In [13]:
d = {'k1':[{'nested key':['this is deep',['hello']]}]}

In [14]:
d

{'k1': [{'nested key': ['this is deep', ['hello']]}]}

In [15]:
d['k1'][0]['nested key'][1]

['hello']

In [16]:
d['k1'][0]['nested key'][1][0]

'hello'

In [17]:
t =[1,1,2,3,4,5,5]

In [18]:
t

[1, 1, 2, 3, 4, 5, 5]

In [33]:
import numpy as np
t= np.array ([[1,2,3,4],[1,2,3,4]])
s = np.array ([[5,6,7,8],[1,2,3,4]])

In [48]:
print(t*s)

[[ 5 12 21 32]
 [ 1  4  9 16]]


In [49]:
2>=3

False

In [51]:
1>=0

True

In [59]:
1<2 or 3<2

True

In [60]:
not 1==1

False

In [75]:
hungree = False
if hungree:
    print("FEED ME!")
else:
    print('I Am not hungree')

I Am not hungree


In [81]:
#if else elif




loc = "Store" 

if loc =="Auto Shop":
    print("Cars are cool")
elif loc =="Bank":
    print("Money is Cool!")
elif loc =="Store":
    print("Welcome to the store!")
else:
    print("I do not no much")

Welcome to the store!


In [88]:
name = 'Chaitanya'


if name =='Frankii':
    print("Hello Frankii!")
elif name == 'Chaitanya':
    print("Hello Chaitanya! How Are you ?")
else:
    print("I want a Authorised user")
    

Hello Chaitanya! How Are you ?


In [90]:
##For looop
mylist =[1,2,3,4,5,6,7,8,9,10]


In [98]:
for num  in mylist:
    print('hello' )

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [103]:
num = 20
for num in mylist:
    if num%2 == 0:
        print(f'Even number:{num}')
    else:
        print(f'Odd number:{num}')

Odd number:1
Even number:2
Odd number:3
Even number:4
Odd number:5
Even number:6
Odd number:7
Even number:8
Odd number:9
Even number:10


In [104]:
list_sum = 0


for num in mylist:
    list_sum = list_sum + num
print(list_sum)

55


In [110]:
mystring = "Hello World"


for _ in "Hello World":
    print("Cool!")

Cool!
Cool!
Cool!
Cool!
Cool!
Cool!
Cool!
Cool!
Cool!
Cool!
Cool!


In [116]:
my_list = [(1,2),(3,4),(5,6),(7,8)]
for (a,b) in my_list:
    print(a)
    print(b)
   

1
2
3
4
5
6
7
8


In [4]:
mystring = 'chaitanya'
for letters in mystring:
    if letters == 'a':
        continue
    print(letters)

c
h
i
t
n
y


In [34]:
print(t)+print(s)

[[1 2 3 4]
 [1 2 3 4]]
[[5 6 7 8]
 [1 2 3 4]]


TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'